### ISSUE TITLE
Possible Use of Incompatibly-Licensed Code

### ISSUE THREAD

**Issue by FoundationGames** [Jordin/fxcr#1]
Hello, I am the developer of [Enhanced Block Entities](https://github.com/FoundationGames/EnhancedBlockEntities), another Minecraft mod.
I have some reason to believe code from Enhanced Block Entities, which is licensed under the [GNU Lesser General Public License v3](https://www.gnu.org/licenses/lgpl-3.0.en.html), has been used directly in FXCR, which is licensed under CC0 a **Public Domain** license and therefore incompatible.

## Example 1
[**Enhanced Block Entities**:](https://github.com/FoundationGames/EnhancedBlockEntities/blob/7b246c0b5e1540ed458aa2ffd8d634365b78ee75/src/main/java/foundationgames/enhancedblockentities/mixin/ChestBlockEntityMixin.java#L19)
![image](https://user-images.githubusercontent.com/43485105/124652897-84671f00-de51-11eb-9432-6da5c21fcbcd.png)
[**FXCR**:](https://github.com/zebp/fxcr/blob/e80e2365b81f89c4b634daf5a3c1c747aff47485/src/main/java/dev/zebulon/fxcr/mixin/MixinChestBlockEntity.java#L25)
![image](https://user-images.githubusercontent.com/43485105/124653154-cd1ed800-de51-11eb-9880-4d556718dc0e.png)
Although one could pass it off as a coincidence, the choice of name and variable type (int) appear very specifically similar to EBE's choice, despite there being little reason to name and type the variable this way.
In EBE specifically the variable was typed as an int, due to me trying to find the correct delay period. That delay period happened to be one tick, meaning that the state of this variable is only ever 1 or 0. I ended up leaving the variable as an int, although reasonably, this variable could have been a boolean type. Yet it happens to be an int in FXCR as well, also with the same variable name.

## Example 2
[**Enhanced Block Entities**:](https://github.com/FoundationGames/EnhancedBlockEntities/blob/7b246c0b5e1540ed458aa2ffd8d634365b78ee75/src/main/java/foundationgames/enhancedblockentities/mixin/ChestBlockEntityMixin.java#L50)
![image](https://user-images.githubusercontent.com/43485105/124653601-58986900-de52-11eb-8a63-095cd8e0b1b6.png)
[**FXCR**:](https://github.com/zebp/fxcr/blob/e80e2365b81f89c4b634daf5a3c1c747aff47485/src/main/java/dev/zebulon/fxcr/mixin/MixinChestBlockEntity.java#L37)
![image](https://user-images.githubusercontent.com/43485105/124653732-81206300-de52-11eb-96fe-757b249c4843.png)
As shown, this appears to be an entire chunk of logic itself which appears to be an exact mirror of that used in EBE. The logic treats rebuildScheduler as a counter, as that was its original purpose in EBE. However as stated before, the maximum value of rebuildScheduler is only ever 1, meaning that this counter logic has no reason to exist, even in EBE. It remains in EBE vestigially, however happens to also be in FXCR, providing reason to believe it was copied.

## Example 3
[**Enhanced Block Entities**:](https://github.com/FoundationGames/EnhancedBlockEntities/blob/7b246c0b5e1540ed458aa2ffd8d634365b78ee75/src/main/java/foundationgames/enhancedblockentities/mixin/ChestBlockEntityMixin.java#L56)
![image](https://user-images.githubusercontent.com/43485105/124654584-93e76780-de53-11eb-8b87-62e5749dd532.png)
[**FXCR**:](https://github.com/zebp/fxcr/blob/e80e2365b81f89c4b634daf5a3c1c747aff47485/src/main/java/dev/zebulon/fxcr/mixin/MixinChestBlockEntity.java#L64)
![image](https://user-images.githubusercontent.com/43485105/124654629-a366b080-de53-11eb-9597-fd6f1dba3ec4.png)
While the methods do in fact perform the same function, that is not as much of a concern as their bearing the same name. This could be a coincidence as well, however given the previous evidence it doesn't seem likely that it is.

The use of LGPLv3 code from Enhanced Block Entities in CC0 software is not compatible.
Some routes you may be able to take to circumvent this licensing issue may include:
- Relicensing the software to a compatible FOSS license
- Rewriting the file of concern

Anyways, thanks in advance and good luck with the project, I hope to hear a response back soon.

**Comment by zebp** [comment]
You are totally right, this is a mistake on my part I didn't consult your license before doing this, I'm sorry. I'm busy for the next few days with work but I can totally do something to fix this during the weekend. Do you have a preference on what you would like me to do, rewrite or relicense?

**Comment by FoundationGames** [comment]
I have no personal preference, you may do what is the easiest for you.

Relicensing the project would involve gathering the consent of all contributors and changing the permissions on the use of the software's code, permanently (as long as EBE's code is still used)

Rewriting the class may be a bit odd to do, as you have used EBE's code and it may be awkward to try and _avoid writing it_, however it means you can keep the public domain license.

And thanks very much for the quick response.

**Comment by jordin** [comment]
Hello, 

Thank you for bringing up this issue. I accept changing the license from Creative Commons Zero v1.0 Universal to GNU Lesser General Public License v3.0. I acknowledge that my contributions (prior and potential future) will be licensed under the GNU Lesser General Public License v3.0.

I believe I am the only other contributor so @zebp should be free to proceed with this change when available.

**Comment by zebp** [comment]
I had some time to mostly rewrite the [file](https://github.com/zebp/fxcr/blob/47436e90485e6492670925d8ea98d7eb6f9135db/src/main/java/dev/zebulon/fxcr/mixin/MixinChestBlockEntity.java), is this adequate to you? I'd rather not re-license unless absolutely necessary but I can if you aren't comfortable with my changes.

**Comment by FoundationGames** [comment]
The file in question appears to no longer contain any trace of EBE's code from what I can see, therefore you may keep your mod public domain with those changes.
Thanks very much!
